### PR TITLE
Update recipe to 1.3.0.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@csadorf I added myself and other signac maintainers to the recipe maintainers list. I won't be able to merge future recipe PRs until I'm added to the maintainers (in this PR).

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Review by csadorf — APPROVED** [review]

**Comment by bdice** [comment]
@csadorf Looks like tests are failing -- I didn't see that after the re-render. I'll change the filelock version. I was trying to match the `~=3.0` specification from the `requirements.txt` file, but conda doesn't support `~=` as a specifier. I made it `>=3.0,<4`. If you have other ideas for how to specify this, let me know. You can test the version specifiers with `conda search "filelock>=3.0,<4"`.

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
@csadorf This PR should be ready to merge. Since I'm not a recipe maintainer, I do not have permissions to merge it (I will get permissions when this PR is merged).

**Pull request merged**
